version: '3.7'

services:
    app:
        build: .
        ports:
            - "5000:5000"
        env_file: .env
        entrypoint: watchmedo auto-restart --recursive --pattern="*.py" --directory="." python3 -- -u futebot/Main.py
        working_dir: /app
        volumes:
            - ./futebot:/app/futebot
        depends_on:
            - db
        environment:
            reddit_client_id: ${reddit_client_id}
            reddit_client_secret: ${reddit_client_secret}
            reddit_username: ${reddit_username}
            reddit_password: ${reddit_password}
            reddit_user_agent: ${reddit_user_agent}
            DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}
            PYTHONUNBUFFERED: 1
        networks:
          - postgres-network
    db:
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            POSTGRES_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_DB: ${POSTGRES_DB}
        networks:
          - postgres-network
    
    pgadmin:
        image: dpage/pgadmin4
        environment:
          PGADMIN_DEFAULT_EMAIL: "root@root.com"
          PGADMIN_DEFAULT_PASSWORD: "123456"
        ports:
          - "16543:80"
        depends_on:
          - db
        networks:
          - postgres-network

networks: 
  postgres-network:
    driver: bridge
